FROM slam-base:latest

RUN apt-get update && apt-get install -y \
    ros-jazzy-ros-gz \
    ros-jazzy-ros-gz-bridge \
    ros-jazzy-gazebo-ros-pkgs \
    ros-jazzy-nav2-bringup \
    ros-jazzy-navigation2

CMD ["bash"]