services:
  dev:
    build:
      context: .
      dockerfile: docker/Dockerfile
    
    image: slam_platform_dev
    container_name: slam_platform
    gpus: all
    hostname: slam_platform
    network_mode: host
    ipc: host
    privileged: true
    stdin_open: true
    tty: true
    restart: unless-stopped
    working_dir: /workspace

    environment:
      DISPLAY: ${DISPLAY}
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID}
      RMW_IMPLEMENTATION: ${RMW_IMPLEMENTATION}
      QT_X11_NO_MITSHM: ${QT_X11_NO_MITSHM}
      LIBGL_ALWAYS_INDIRECT: ${LIBGL_ALWAYS_INDIRECT}
      NVIDIA_VISIBLE_DEVICES: ${NVIDIA_VISIBLE_DEVICES}
      NVIDIA_DRIVER_CAPABILITIES: ${NVIDIA_DRIVER_CAPABILITIES}

    volumes:
      - ./slam_ws:/workspace/slam_ws
      - ./plugin_ws:/workspace/plugin_ws
      - ./datasets:/workspace/datasets
      - ./scripts:/workspace/scripts
      - ./results:/workspace/results
      - ./logs:/workspace/logs
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev

    command: bash